import express, { Express, Request, Response, NextFunction } from 'express';
import { initCronJobs } from "./services/cronJobs";
import cors from 'cors';
import dotenv from 'dotenv';
import { Pool } from 'pg';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import morgan from 'morgan';
import helmet from 'helmet';
import compression from 'compression';
